### ISSUE TITLE
Expiration Time Incorrect

### ISSUE THREAD

**Issue by Toeler** [W00dL3cs/pokego-explorer#3]
The Pokemon.ExpirationTimeMs is number of ms since epoch and so creating a new DateTime object with the ms results in the wrong value. new DateTime(1970, 1, 1).AddMilliseconds(Pokemon.ExpirationTimeMs) gives the correct value.

**Comment by W00dL3cs** [comment]
Thank you, went so fast writing the code I didn't even realise it showed the wrong time.
Gonna fix it as soon as possible :)

**Comment by Toeler** [comment]
Don't forget UTC as well.
