### ISSUE TITLE
Use 0.00375 instead of 0.0025 for Longitude.

### ISSUE THREAD

**Issue by Megurine** [W00dL3cs/pokego-explorer#6]
Hi, to get a square on the map, its better to use : 
`NEXT_X = (X * 0.0025) + Latitude;
                NEXT_Y = (Y * 0.00375) + Longitude;`
in the Exploration.Helper.cs

"0.0025,0.0025" gives you a vertical rectangle.

**Comment by W00dL3cs** [comment]
Thank you :)
