### ISSUE TITLE
hearthranger

### ISSUE THREAD

**Issue by godshades** [W00dL3cs/pokego-explorer#8]
sorry, can you share the bypass version of this
https://www.nulledblog.com/topic/136093-request-hearthranger-account-to-complete-cracking-process/

**Comment by W00dL3cs** [comment]
This is not exactly the right place to ask for something like that.

By the way, I don't own the code anymore: and even if I did, I guess it would have been patched already (considering an year has passed).

I'm going to close this issue request, as I'm scared I cannot help you with the matter.
